name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      # You can override these in the repo’s Settings → Secrets if you like
      API_IMAGE: healthmlopsx-api
      UI_IMAGE:  healthmlopsx-frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Run tests
        working-directory: .
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build backend Docker image
        run: |
          docker build \
            --file docker/Dockerfile.api \
            --tag ${{ env.API_IMAGE }}:${{ github.sha }} \
            --tag ${{ env.API_IMAGE }}:latest \
            .

      - name: Build frontend Docker image
        run: |
          docker build \
            --file docker/Dockerfile.frontend \
            --tag ${{ env.UI_IMAGE }}:${{ github.sha }} \
            --tag ${{ env.UI_IMAGE }}:latest \
            .

      # Optional: push to Docker Hub or GitHub Packages
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Push backend image
      #   run: |
      #     docker push ${{ env.API_IMAGE }}:latest
      #     docker push ${{ env.API_IMAGE }}:${{ github.sha }}
      #
      # - name: Push frontend image
      #   run: |
      #     docker push ${{ env.UI_IMAGE }}:latest
      #     docker push ${{ env.UI_IMAGE }}:${{ github.sha }}
